### ISSUE TITLE
will it import for both users?

### ISSUE THREAD

**Issue by lorvent** [realdeveloperongithub/chat-history-manager#1]
Hello,
I have a Question...

Will it import only for me or also for other user too?

thanks.

**Comment by lorvent** [comment]
Bro....can you respond?

this is really really important for me.

thanks.

**Comment by realdeveloperongithub** [comment]
It will import for the other user too.
Telegram will sync the chat history

**Comment by realdeveloperongithub** [comment]
> Bro....can you respond?
> 
> this is really really important for me.
> 
> thanks.

It will import for the other user too.
Telegram will sync the chat history

**Comment by lorvent** [comment]
> > Bro....can you respond?
> > this is really really important for me.
> > thanks.
> 
> It will import for the other user too. Telegram will sync the chat history

wow...thats a great news!

I will try it out!

thank you!
